uploads = []
generated = []

[[outputs]]
id = "yJk1CT0be-Sk4wIyCRpDI"
uri = "file://DEPLOY-OVH.md"
type = "text"
title = "Guide de déploiement OVH"
description = "Documentation Markdown avec la consigne de préserver CitiZarm lors du déploiement d’un autre projet."
logical_id = "3f0c3fd4-edb3-4d09-8d59-8f7b2f858f51"
content_hash = "sha256:d06e3d79ad75c88ac86a4a4559998a37f98c661784dcaec21e295bd03cae90b7"
size = 19351
mtime_ms = 1791495482730
storage_uri = "gcs://replit-rams-assets-picard/rams/assets/repl:9b04f0e6-80dd-45e4-a327-afeb38240dbb/3f0c3fd4-edb3-4d09-8d59-8f7b2f858f51/4cdf13f6-b451-4eaf-804f-51e5c67a6c11"
storage_version_token = "1791495792087458"
content_type = "text/markdown"

[[outputs]]
id = "Qp553gAQm5NxerxPy6wMp"
uri = "file://downloads/guide-deploiement-ovh.zip"
type = "unspecified"
title = "Guide OVH CitiZarm — maintenance et sauvegardes"
description = "Guide actualisé avec le rôle de restart et les modifications nécessaires pour sauvegarder toutes les bases du serveur."
logical_id = "a7b222d4-1021-4147-996f-8c9feaa875a5"
content_hash = "sha256:6637a1331317e30b18d52b4d8f182d486196593142c7190482f211a24250cb07"
size = 11621
mtime_ms = 1791499607519
storage_uri = "gcs://replit-rams-assets-picard/rams/assets/repl:9b04f0e6-80dd-45e4-a327-afeb38240dbb/a7b222d4-1021-4147-996f-8c9feaa875a5/6af71b5c-a156-4347-a860-f0f449c9f62b"
storage_version_token = "1791499616062923"
content_type = "application/octet-stream"
